<a href="https://colab.research.google.com/github/VedantMadane/maha/blob/main/05_VectorizeText_for_DataMining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vectorize Text Using Different Techniques for Data Mining the Mahābhārata

In [ ]:
import sklearn

print(sklearn.__version__)

0.20.3


In [9]:
with open('/content/drive/MyDrive/beproject/rawdata/maha01.txt') as f:
  maha01 = f.read()
with open('/content/drive/MyDrive/beproject/rawdata/maha02.txt') as f:
  maha02 = f.read()
with open('/content/drive/MyDrive/beproject/rawdata/maha03.txt') as f:
  maha03 = f.read()
with open('/content/drive/MyDrive/beproject/rawdata/maha04.txt') as f:
  maha04 = f.read()
with open('/content/drive/MyDrive/beproject/rawdata/maha05.txt') as f:
  maha05 = f.read()
with open('/content/drive/MyDrive/beproject/rawdata/maha06.txt') as f:
  maha06 = f.read()
with open('/content/drive/MyDrive/beproject/rawdata/maha07.txt') as f:
  maha07 = f.read()
with open('/content/drive/MyDrive/beproject/rawdata/maha08.txt') as f:
  maha08 = f.read()
with open('/content/drive/MyDrive/beproject/rawdata/maha09.txt') as f:
  maha09 = f.read()
with open('/content/drive/MyDrive/beproject/rawdata/maha10.txt') as f:
  maha10 = f.read()
with open('/content/drive/MyDrive/beproject/rawdata/maha11.txt') as f:
  maha11 = f.read()
with open('/content/drive/MyDrive/beproject/rawdata/maha12.txt') as f:
  maha12 = f.read()
with open('/content/drive/MyDrive/beproject/rawdata/maha13.txt') as f:
  maha13 = f.read()
with open('/content/drive/MyDrive/beproject/rawdata/maha14.txt') as f:
  maha14 = f.read()
with open('/content/drive/MyDrive/beproject/rawdata/maha15.txt') as f:
  maha15 = f.read()
with open('/content/drive/MyDrive/beproject/rawdata/maha16.txt') as f:
  maha16 = f.read()
with open('/content/drive/MyDrive/beproject/rawdata/maha17.txt') as f:
  maha17 = f.read()
with open('/content/drive/MyDrive/beproject/rawdata/maha18.txt') as f:
  maha18 = f.read()

### CountVectorizer

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
train_text = [maha01, maha02, maha03, maha04, maha05, maha06, maha07, maha08, maha09, maha10, maha11, maha12,
              maha13, maha14, maha15, maha16, maha17, maha18
             ]

count_vectorizer = CountVectorizer()

In [12]:
count_vectorizer.fit(train_text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [14]:
count_vectorizer.vocabulary_

{'the': 29264,
 'mahabharata': 18216,
 'of': 20434,
 'krishna': 17050,
 'dwaipayana': 10782,
 'vyasa': 32588,
 'book': 5651,
 'adi': 2447,
 'parva': 21204,
 'translated': 29734,
 'into': 15625,
 'english': 11289,
 'prose': 22954,
 'from': 12823,
 'original': 20619,
 'sanskrit': 25531,
 'text': 29253,
 'by': 6077,
 'kisari': 16916,
 'mohan': 19274,
 'ganguli': 13023,
 '1883': 989,
 '1896': 1003,
 'scanned': 26000,
 'at': 4238,
 'sacred': 24962,
 'texts': 29254,
 'com': 7433,
 '2003': 1066,
 'proofed': 22904,
 'distributed': 10275,
 'proofing': 22905,
 'juliet': 16142,
 'sutherland': 28571,
 'project': 22855,
 'manager': 18471,
 'additional': 2372,
 'and': 3210,
 'formatting': 12664,
 'hare': 13910,
 'translator': 29739,
 'preface': 22541,
 'object': 20320,
 'should': 26565,
 'ever': 11624,
 'be': 4849,
 'to': 29527,
 'hold': 14377,
 'mirror': 19121,
 'upto': 30995,
 'his': 14350,
 'author': 4466,
 'that': 29262,
 'being': 4995,
 'so': 27093,
 'chief': 6966,
 'duty': 10773,
 'is': 15761,

In [15]:
count_vectorizer.vocabulary_.get('world')

33168

In [16]:
transformed_vector = count_vectorizer.transform(train_text)

In [17]:
print(transformed_vector.shape)

(18, 33625)


In [20]:
print(transformed_vector.toarray())

[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 4 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]]


In [21]:
test_text = ["Don't cry because it's over, smile because it happened."]

count_vectorizer.transform(test_text).toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [22]:
count_vectorizer.fit(train_text + test_text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [23]:
print(count_vectorizer.vocabulary_)

{'the': 29264, 'mahabharata': 18216, 'of': 20434, 'krishna': 17050, 'dwaipayana': 10782, 'vyasa': 32588, 'book': 5651, 'adi': 2447, 'parva': 21204, 'translated': 29734, 'into': 15625, 'english': 11289, 'prose': 22954, 'from': 12823, 'original': 20619, 'sanskrit': 25531, 'text': 29253, 'by': 6077, 'kisari': 16916, 'mohan': 19274, 'ganguli': 13023, '1883': 989, '1896': 1003, 'scanned': 26000, 'at': 4238, 'sacred': 24962, 'texts': 29254, 'com': 7433, '2003': 1066, 'proofed': 22904, 'distributed': 10275, 'proofing': 22905, 'juliet': 16142, 'sutherland': 28571, 'project': 22855, 'manager': 18471, 'additional': 2372, 'and': 3210, 'formatting': 12664, 'hare': 13910, 'translator': 29739, 'preface': 22541, 'object': 20320, 'should': 26565, 'ever': 11624, 'be': 4849, 'to': 29527, 'hold': 14377, 'mirror': 19121, 'upto': 30995, 'his': 14350, 'author': 4466, 'that': 29262, 'being': 4995, 'so': 27093, 'chief': 6966, 'duty': 10773, 'is': 15761, 'represent': 24237, 'far': 12088, 'as': 3913, 'practicab

In [24]:
count_vectorizer.transform(test_text).toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [25]:
count_vectorizer.inverse_transform(transformed_vector)

[array(['10th', '11th', '12th', ..., 'yuyudhana', 'yuyutsu', 'zodiac'],
       dtype='<U31'),
 array(['1883', '1896', '2003', ..., 'yugas', 'yuyudhana', 'zenana'],
       dtype='<U31'),
 array(['10', '100', '101', ..., 'yuyudhana', 'yuyutshu', 'zarathustra'],
       dtype='<U31'),
 array(['10', '11', '12', ..., 'yuyudhana', 'zealously', 'zone'],
       dtype='<U31'),
 array(['10', '11', '12', ..., 'yuyutsu', 'zealously', 'zodiac'],
       dtype='<U31'),
 array(['10', '100', '101', ..., 'yuvutsu', 'yuyudhana', 'yuyutsu'],
       dtype='<U31'),
 array(['10', '100', '101', ..., 'yuyudhana', 'yuyutsu', 'zeal'],
       dtype='<U31'),
 array(['00', '000', '10', ..., 'yuyudhana', 'yuyutsu', 'zealously'],
       dtype='<U31'),
 array(['000', '10', '100', ..., 'yuga', 'yuyudhana', 'yuyutsu'],
       dtype='<U31'),
 array(['000', '10', '11', ..., 'yudhishthira', 'yuga', 'yuyudhana'],
       dtype='<U31'),
 array(['000', '10', '11', ..., 'yuga', 'yuyudhana', 'yuyutsu'],
       dtype='<U31'),
 arr

### CountVectorizer using n-grams

In [26]:
n_gram_vectorizer = CountVectorizer(ngram_range=(2, 2))

In [27]:
transformed_vector = n_gram_vectorizer.fit_transform(train_text)

transformed_vector.shape

(18, 547101)

In [28]:
n_gram_vectorizer.vocabulary_

{'the mahabharata': 451403,
 'mahabharata of': 278427,
 'of krishna': 317946,
 'krishna dwaipayana': 260716,
 'dwaipayana vyasa': 146385,
 'vyasa book': 511093,
 'book adi': 79664,
 'adi parva': 13339,
 'parva translated': 340113,
 'translated into': 484636,
 'into english': 240763,
 'english prose': 154743,
 'prose from': 358612,
 'from the': 186332,
 'the original': 452114,
 'original sanskrit': 331012,
 'sanskrit text': 390632,
 'text by': 442550,
 'by kisari': 89817,
 'kisari mohan': 259062,
 'mohan ganguli': 293874,
 'ganguli 1883': 189331,
 '1883 1896': 2822,
 '1896 scanned': 2857,
 'scanned at': 393931,
 'at sacred': 55057,
 'sacred texts': 384785,
 'texts com': 442631,
 'com 2003': 106357,
 '2003 proofed': 3114,
 'proofed at': 357908,
 'at distributed': 54778,
 'distributed proofing': 138409,
 'proofing juliet': 357911,
 'juliet sutherland': 250740,
 'sutherland project': 437416,
 'project manager': 357647,
 'manager additional': 280917,
 'additional proofing': 12693,
 'proofin

In [29]:
transformed_vector.toarray()

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [30]:
n_gram_vectorizer.inverse_transform(transformed_vector)

[array(['the mahabharata', 'mahabharata of', 'of krishna', ...,
        'parva footnotes', 'footnotes these', 'are divisions'],
       dtype='<U42'),
 array(['the mahabharata', 'mahabharata of', 'of krishna', ...,
        'footnotes word', 'benediction similar', 'to amen'], dtype='<U42'),
 array(['the mahabharata', 'mahabharata of', 'of krishna', ...,
        'bluntness of', 'mortal feeling', 'feeling decrepitude'],
       dtype='<U42'),
 array(['the mahabharata', 'mahabharata of', 'of krishna', ...,
        'justify that', 'that presence', 'following sentences'],
       dtype='<U42'),
 array(['the mahabharata', 'mahabharata of', 'of krishna', ...,
        'mahishmati on', 'narmada nerbuda', 'nerbuda was'], dtype='<U42'),
 array(['the mahabharata', 'mahabharata of', 'of krishna', ...,
        'bravery on', 'always thus', 'thus rewarded'], dtype='<U42'),
 array(['the mahabharata', 'mahabharata of', 'of krishna', ..., '274 all',
        'terms imply', 'imply death'], dtype='<U42'),
 arra

### TfidfVectorizer

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()

In [32]:
tfidf_vector = tfidf_vectorizer.fit_transform(train_text)

tfidf_vectorizer.vocabulary_

{'the': 29264,
 'mahabharata': 18216,
 'of': 20434,
 'krishna': 17050,
 'dwaipayana': 10782,
 'vyasa': 32588,
 'book': 5651,
 'adi': 2447,
 'parva': 21204,
 'translated': 29734,
 'into': 15625,
 'english': 11289,
 'prose': 22954,
 'from': 12823,
 'original': 20619,
 'sanskrit': 25531,
 'text': 29253,
 'by': 6077,
 'kisari': 16916,
 'mohan': 19274,
 'ganguli': 13023,
 '1883': 989,
 '1896': 1003,
 'scanned': 26000,
 'at': 4238,
 'sacred': 24962,
 'texts': 29254,
 'com': 7433,
 '2003': 1066,
 'proofed': 22904,
 'distributed': 10275,
 'proofing': 22905,
 'juliet': 16142,
 'sutherland': 28571,
 'project': 22855,
 'manager': 18471,
 'additional': 2372,
 'and': 3210,
 'formatting': 12664,
 'hare': 13910,
 'translator': 29739,
 'preface': 22541,
 'object': 20320,
 'should': 26565,
 'ever': 11624,
 'be': 4849,
 'to': 29527,
 'hold': 14377,
 'mirror': 19121,
 'upto': 30995,
 'his': 14350,
 'author': 4466,
 'that': 29262,
 'being': 4995,
 'so': 27093,
 'chief': 6966,
 'duty': 10773,
 'is': 15761,

In [33]:
tfidf_vector.shape

(18, 33625)

In [34]:
tfidf_vector.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.00011077,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.00698197, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.01015132, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.00524936, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [35]:
tfidf_vectorizer.idf_

array([3.2512918 , 1.7472144 , 3.2512918 , ..., 3.2512918 , 2.84582669,
       3.2512918 ])

In [36]:
dict(zip(tfidf_vectorizer.get_feature_names(), tfidf_vectorizer.idf_))

{'00': 3.2512917986064953,
 '000': 1.7472144018302211,
 '01': 3.2512917986064953,
 '10': 1.3053816495511819,
 '100': 1.7472144018302211,
 '1000': 3.2512917986064953,
 '1001': 3.2512917986064953,
 '1002': 3.2512917986064953,
 '1003': 3.2512917986064953,
 '1004': 3.2512917986064953,
 '1005': 3.2512917986064953,
 '1006': 3.2512917986064953,
 '1007': 3.2512917986064953,
 '1008': 3.2512917986064953,
 '1009': 3.2512917986064953,
 '101': 1.9985288301111273,
 '1010': 3.2512917986064953,
 '1011': 3.2512917986064953,
 '1012': 3.2512917986064953,
 '1013': 3.2512917986064953,
 '1014': 3.2512917986064953,
 '1015': 3.2512917986064953,
 '1016': 3.2512917986064953,
 '1017': 3.2512917986064953,
 '1018': 3.2512917986064953,
 '1019': 3.2512917986064953,
 '102': 1.9985288301111273,
 '1020': 3.2512917986064953,
 '1021': 3.2512917986064953,
 '1022': 3.2512917986064953,
 '1023': 3.2512917986064953,
 '1024': 3.2512917986064953,
 '1025': 3.2512917986064953,
 '1026': 3.2512917986064953,
 '1027': 3.2512917986064

In [37]:
tfidf_vectorizer.inverse_transform(tfidf_vector)

[array(['assurances', 'resentment', 'harbour', ..., 'of', 'mahabharata',
        'the'], dtype='<U31'),
 array(['amen', 'gavalgani', 'response', ..., 'of', 'mahabharata', 'the'],
       dtype='<U31'),
 array(['bluntness', 'cosmogony', 'footnote', ..., 'of', 'mahabharata',
        'the'], dtype='<U31'),
 array(['sentences', 'justify', 'imprudently', ..., 'of', 'mahabharata',
        'the'], dtype='<U31'),
 array(['nerbuda', 'kartaviryarjuna', 'astras', ..., 'of', 'mahabharata',
        'the'], dtype='<U31'),
 array(['tarkitas', 'kururajasya', 'ddhwaja', ..., 'of', 'mahabharata',
        'the'], dtype='<U31'),
 array(['yonim', 'fabled', 'bhuyopi', ..., 'of', 'mahabharata', 'the'],
       dtype='<U31'),
 array(['parv', 'musing', 'dvaipayana', ..., 'of', 'mahabharata', 'the'],
       dtype='<U31'),
 array(['keenly', 'murky', 'husbandless', ..., 'of', 'mahabharata', 'the'],
       dtype='<U31'),
 array(['shrunk', 'menjavat', 'adopter', ..., 'of', 'mahabharata', 'the'],
       dtype='<U31'),

### HashingVectorizer

In [38]:
from sklearn.feature_extraction.text import HashingVectorizer

hashing_vectorizer = HashingVectorizer(n_features=16, norm=None)
feature_vector = hashing_vectorizer.transform(train_text)

feature_vector.shape

(18, 16)

In [39]:
feature_vector.toarray()

array([[ 4.1260e+03,  4.6290e+03,  1.5400e+02,  1.8130e+03, -2.0770e+03,
         2.0930e+03,  2.6900e+02, -1.0470e+03, -4.1330e+03, -2.2000e+01,
         6.1800e+02,  7.4910e+03,  1.2306e+04, -6.9470e+03, -1.3453e+04,
        -3.2780e+03],
       [ 1.2330e+03,  1.4980e+03,  9.7000e+01,  4.0200e+02, -6.8600e+02,
         4.5600e+02,  4.2100e+02, -2.6100e+02, -1.7780e+03,  2.4200e+02,
        -2.7200e+02,  2.4700e+03,  4.2970e+03, -2.8440e+03, -4.1870e+03,
        -1.3120e+03],
       [ 5.8610e+03,  6.3350e+03,  1.7200e+02,  2.4700e+03, -3.9010e+03,
         2.7230e+03,  1.0230e+03, -1.4250e+03, -6.0670e+03,  3.3100e+02,
         3.5400e+02,  1.2003e+04,  1.6131e+04, -1.2762e+04, -1.8532e+04,
        -5.2630e+03],
       [ 1.0210e+03,  1.3610e+03,  2.0000e+00,  4.7200e+02, -4.0200e+02,
         3.7600e+02,  9.0000e+00, -4.2100e+02, -1.6530e+03,  3.8500e+02,
         2.5300e+02,  1.7070e+03,  3.3910e+03, -2.4660e+03, -3.5590e+03,
        -8.2800e+02],
       [ 3.3180e+03,  4.0630e+03, -5

In [40]:
hashing_vectorizer = HashingVectorizer(n_features=16, norm='l1')
feature_vector = hashing_vectorizer.transform(train_text)

feature_vector.shape

(18, 16)

In [41]:
feature_vector.toarray()

array([[ 6.40126598e-02,  7.18164329e-02,  2.38922676e-03,
         2.81277150e-02, -3.22235323e-02,  3.24717637e-02,
         4.17338960e-03, -1.62436391e-02, -6.41212610e-02,
        -3.41318108e-04,  9.58793596e-03,  1.16218816e-01,
         1.90920938e-01, -1.07778950e-01, -2.08716023e-01,
        -5.08563982e-02],
       [ 5.49073744e-02,  6.67082294e-02,  4.31955825e-03,
         1.79016744e-02, -3.05486284e-02,  2.03063769e-02,
         1.87477734e-02, -1.16227289e-02, -7.91770574e-02,
         1.07766299e-02, -1.21125757e-02,  1.09992875e-01,
         1.91351977e-01, -1.26647667e-01, -1.86453509e-01,
        -5.84253652e-02],
       [ 6.14663409e-02,  6.64373433e-02,  1.80382369e-03,
         2.59037471e-02, -4.09111407e-02,  2.85570459e-02,
         1.07285560e-02, -1.49444695e-02, -6.36267343e-02,
         3.47131186e-03,  3.71252084e-03,  1.25879626e-01,
         1.69171395e-01, -1.33839523e-01, -1.94351515e-01,
        -5.51949073e-02],
       [ 5.57740631e-02,  7.43472086e

In [42]:
hashing_vectorizer = HashingVectorizer(n_features=16, norm='l2')
feature_vector = hashing_vectorizer.transform(train_text)

feature_vector.shape

(18, 16)

In [43]:
feature_vector.toarray()

array([[ 1.81525983e-01,  2.03655786e-01,  6.77532752e-03,
         7.97640831e-02, -9.13789303e-02,  9.20828604e-02,
         1.18348253e-02, -4.60634280e-02, -1.81833952e-01,
        -9.67903932e-04,  2.71893013e-02,  3.29571289e-01,
         5.41410263e-01, -3.05637664e-01, -5.91873254e-01,
        -1.44217686e-01],
       [ 1.59101688e-01,  1.93296293e-01,  1.25165156e-02,
         5.18725698e-02, -8.85188629e-02,  5.88405270e-02,
         5.43242584e-02, -3.36784595e-02, -2.29426441e-01,
         3.12267709e-02, -3.50978582e-02,  3.18719521e-01,
         5.54468738e-01, -3.66979076e-01, -5.40274751e-01,
        -1.69295551e-01],
       [ 1.78208381e-01,  1.92620730e-01,  5.22979724e-03,
         7.51023208e-02, -1.18613018e-01,  8.27949877e-02,
         3.11051312e-02, -4.33282620e-02, -1.84471976e-01,
         1.00643191e-02,  1.07636525e-02,  3.64960792e-01,
         4.90475926e-01, -3.88038793e-01, -5.63480247e-01,
        -1.60025714e-01],
       [ 1.60656082e-01,  2.14155658e

In [47]:
!pip install jovian
import jovian
jovian.commit()

     |████████████████████████████████| 71kB 3.3MB/s 
  Created wheel for uuid: filename=uuid-1.30-cp37-none-any.whl size=6503 sha256=305601005dc17a33ec2a200ffc0c58a57b5133b4d00159d28108cab17df8294f
  Stored in directory: /root/.cache/pip/wheels/2a/80/9b/015026567c29fdffe31d91edbe7ba1b17728db79194fca1f21
Successfully built uuid


[jovian] Detected Colab notebook...


[jovian] Error: jovian.commit doesn't work on Colab unless the notebook was created and executed from Jovian.
Make sure to run the first code cell at the top after executing from Jovian.
Alternatively, you can download this notebook and upload it manually to Jovian.
Learn more: https://jovian.ai/docs/user-guide/run.html#run-on-colab
